blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/tacy-OPS/terraform-provider-valohai/discussions
    about: Ask questions and get help in the Discussions tab.
